export const LOAD_TENANT_SETTINGS = 'app/App/LOAD_TENANT_SETTINGS';
export const LOAD_TENANT_SETTINGS_SUCCESS = 'app/App/LOAD_TENANT_SETTINGS_SUCCESS';
export const LOAD_TENANT_SETTINGS_FAILURE = 'app/App/LOAD_TENANT_SETTINGS_FAILURE';